### ISSUE TITLE
Failed to parse level range on german client

### ISSUE THREAD

**Issue by cbracht** [Treeston/SummonStoneHelper#1]
Hello,

the tooltip is malformatted in german as it seems (your addon is the only one loaded):
![image](https://user-images.githubusercontent.com/1489764/156417447-f82258ae-6e06-4b09-bbb0-22d1c6e36f61.png)

When hovering over the summoning stone for the first time, the addon raises an error:
![image](https://user-images.githubusercontent.com/1489764/156417574-9836b1c7-620f-4fc6-b440-181acbc32430.png)

The addon seems not to work without being able to parse a level range, as no tooltip/popup is showing when hovering over the summoning stone.

Thank you for your time and with best Regards!

**Comment by Treeston** [comment]
...did Blizzard really mess up their German format string for summoning stone tooltips?

Is that "level range" shown the same for every stone in that locale?

**Comment by Treeston** [comment]
PS the addon _should_ work fine even if it fails to detect the level range. Are you sure that there are non-dead players that are not already in/near Caverns of Time?

**Comment by cbracht** [comment]
At least for me and my german client every tooltip has the 1d-2d showing as level range:
![image](https://user-images.githubusercontent.com/1489764/156610353-3293570d-8179-4982-b089-da2e8bf50758.png)

With no other addons and one other living person in group when testing with switch /console scriptErrors 1

- I get serveral start up errors due to libraries not found e.g.
![image](https://user-images.githubusercontent.com/1489764/156609985-29c51483-c3eb-4a9b-9d80-65a45f98f86d.png)

- On hovering over the summoning stone, the following error is thrown (possibly related to missing libraries):
![image](https://user-images.githubusercontent.com/1489764/156609387-0d92dd3f-db16-4d46-b68c-c532ac09694a.png)

With other addons enabled:
- No startup errors
- On hovering over the summoning stone, the following error is thrown:
![image](https://user-images.githubusercontent.com/1489764/156610560-b57e2cc6-4ced-47f3-ad33-dbf41996bffc.png)

**Comment by Treeston** [comment]
> At least for me and my german client every tooltip has the 1d-2d showing as level range:

Yeah, that's a Blizzard-side bug then. I'll add a workaround to avoid showing the error for that particular screw-up.

For the actual error that's preventing the addon from working, I'll need investigate. Thanks a lot for the thorough report!

**Comment by cbracht** [comment]
Thank you very much, the changes work for me when I have my other addons enabled and the addon is working as expected now.

Fyi, when running the addon without any other addons enabled, the following errors are thrown:
![image](https://user-images.githubusercontent.com/1489764/156873014-315ebbdf-1fdb-4f45-a250-9d8ea869cd5d.png)
![image](https://user-images.githubusercontent.com/1489764/156873021-4a1493a8-e20a-495c-9cd8-ee0489d13c43.png)
![image](https://user-images.githubusercontent.com/1489764/156873027-e64bb2f7-527a-47d0-92ef-aa135d7843af.png)

**Comment by Treeston** [comment]
Is that with the addon checked out from the repository, rather then the packaged version from Curse?

**Comment by cbracht** [comment]
Checked out from the repository and copied to the existing folder as release ist not available yet on curseforge

**Comment by Treeston** [comment]
Repository clones won't have the necessary dependencies embedded in them, those are added by the Curseforge packager (which appears to be having some issues right now). They're designed to be run with standalone versions of the necessary libraries being installed.

**Comment by Treeston** [comment]
Curseforge packager issues resolved, `1.0.2a` is now available and should not produce any errors if loaded standalone.

**Comment by cbracht** [comment]
Release 1.0.2a is fully functional, thank you very much!
